// ─── ENERGY + KNAPSACK OPTIMIZER ─────────────────────────

import { Card, CardDb, CardEffect } from "./cards.js";

// Compile-time exhaustiveness guard. Pass the narrowed-to-never discriminant
// so TypeScript errors if any CardEffect variant is missing from a switch.
function assertNever(x: never): never {
  throw new Error(`Unhandled CardEffect type: ${(x as { type: string }).type}`);
}

export interface PlayerState {
  readonly strength:       number;
  readonly vulnerableStacks: number;   // current enemy vulnerable stacks (0 = not vulnerable; 1.5× damage if >0)
  readonly weak:           boolean;
  readonly frail:          boolean;   // player is frail (block from cards ×0.75)
  readonly focus:          number;
  readonly poisonTriggers: number;
  readonly exhaust:              number;
  readonly blockPerExhaustEvent: number;   // Feel No Pain passive: block gained per exhaust event
  readonly drawPerExhaustEvent:  number;   // Dark Embrace passive: cards drawn per exhaust event
  readonly damagePerBlockGain:   number;   // Grapple passive: flat damage dealt per block gain event this turn
  readonly damagePerHpLoss:      number;   // Inferno passive: flat damage dealt per HP loss event this turn
  readonly exhaustedThisTurn:    boolean;  // true if any card was exhausted this turn (for Evil Eye)
  readonly currentBlock:         number;
  readonly energyRemaining: number;
  readonly enemyAttack:     number;
  readonly enemyHits:      number;
  readonly enemyWeak:      boolean;
  readonly enemyStrength:   number;   // enemy's current strength (flat bonus to their attack damage per hit)
  readonly selfDamageThisTurn: number;     // HP lost to self-damage cards played this turn
  readonly attacksPlayedThisTurn: number;  // attack cards played so far this turn (for Stomp cost reduction)
  readonly nextAttackFree: boolean;        // true if the next attack played this turn costs 0 (e.g. Unrelenting)
  readonly noMoreDraws: boolean;           // true after Battle Trance is played; all subsequent draw effects are skipped
  readonly corruptionActive: boolean;      // true after Corruption is played; skills cost 0 and exhaust
  readonly vulnMultBonus: number;          // added to base 1.5× vulnerable multiplier (e.g. Cruelty: +0.25 / +0.5)
  readonly hellraiserActive: boolean;      // true after Hellraiser is played; drawn Strike cards auto-play for free
  readonly freeGeneratedCard: string | null;  // name of the card generated by Infernal Blade (free this turn); null = no free card
  readonly copyAttackOnN: number;          // Juggling passive: copy the Nth attack played to hand (0 = inactive)
  readonly doubleNextAttacks: number;      // remaining attacks that trigger twice this turn (0 = inactive)
  readonly blockPerAttackPlayed: number;   // Rage passive: block gained each time an attack is played this turn
  readonly rampageDamageBonus: number;     // Rampage: accumulated +damage from all Rampage plays so far this combat
  readonly strengthPerHpLoss: number;      // Rupture passive: gain this much strength each time you lose HP
  readonly stampedeCount: number;          // Stampede: number of end-of-turn attack triggers (0 = inactive)
  readonly plating: number;                // Plating stacks: end of turn gain this much block, then stacks -1
  readonly hpLossCount: number;           // HP loss events this combat (from enemies + self-damage); set via --hp-loss-count
  readonly totalCardsAnywhere: number;     // total cards across all zones (hand+draw+discard+exhaust+powers); set by DFS for Perfected Strike
  readonly thrashDamageBonus: number;      // Thrash: accumulated base-damage bonus from prior Thrash exhausts this turn
  readonly doubleNextBlockCard: boolean;   // Unmovable: true until the first block-effect card is played this turn
}

export function defaultPlayerState(): PlayerState {
  return {
    strength:             0,
    vulnerableStacks:     0,
    weak:                 false,
    frail:                false,
    focus:                0,
    poisonTriggers:       1,
    exhaust:              0,
    blockPerExhaustEvent: 0,
    drawPerExhaustEvent:  0,
    damagePerBlockGain:   0,
    damagePerHpLoss:      0,
    exhaustedThisTurn:    false,
    currentBlock:         0,
    energyRemaining:      0,
    enemyAttack:          0,
    enemyHits:            1,
    enemyWeak:            false,
    enemyStrength:        0,
    selfDamageThisTurn:   0,
    attacksPlayedThisTurn: 0,
    nextAttackFree:       false,
    noMoreDraws:          false,
    corruptionActive:     false,
    vulnMultBonus:        0,
    hellraiserActive:     false,
    freeGeneratedCard:    null,
    copyAttackOnN:        0,
    doubleNextAttacks:    0,
    blockPerAttackPlayed: 0,
    rampageDamageBonus:   0,
    strengthPerHpLoss:    0,
    stampedeCount:        0,
    plating:              0,
    hpLossCount:          0,
    totalCardsAnywhere:   0,
    thrashDamageBonus:    0,
    doubleNextBlockCard:  false,
  };
}

export interface ComboResult {
  totalDamage: number;
  totalBlock:  number;
}

export interface CardValues {
  damage: number;
  block:  number;
}

export type Mode = "dmg" | "block";

// Base passive damage/block for each orb type (before Focus)
const ORB_BASE: Record<string, { damage: number; block: number }> = {
  lightning: { damage: 3, block: 0 },
  frost:     { damage: 0, block: 2 },
};

// Compute the effective damage and block a card contributes given player state.
export function cardEffectiveValues(card: Card, player: PlayerState): CardValues {
  // Energy constraint: when tracking energy (energyRemaining > 0), an unaffordable
  // card contributes nothing. energyRemaining = 0 means not tracking (legacy / default).
  const effectiveCardCost = (card.type === "attack" && player.nextAttackFree) || (card.type === "skill" && player.corruptionActive)
    ? 0
    : card.costReductionPerAttack > 0
      ? Math.max(0, card.cost - player.attacksPlayedThisTurn * card.costReductionPerAttack)
      : card.cost;
  if (player.energyRemaining > 0 && effectiveCardCost > player.energyRemaining) {
    return { damage: 0, block: 0 };
  }
  const { strength, vulnerableStacks, weak, frail, focus, poisonTriggers, exhaust } = player;
  const vulnMult  = vulnerableStacks > 0 ? 1.5 + player.vulnMultBonus : 1;
  const weakMult  = weak  ? 0.75 : 1;
  const frailMult = frail ? 0.75 : 1;

  // Pre-compute exhaust bonus — adds to the base of any attack damage this card deals
  const exBonusEff = card.effects.find(e => e.type === "exhaust_bonus") as
    Extract<CardEffect, { type: "exhaust_bonus" }> | undefined;
  const exhaustBonus = exBonusEff ? exBonusEff.amount * exhaust : 0;

  // Pre-compute per-card-anywhere bonus (Perfected Strike) — same treatment as exhaustBonus
  const perCardEff = card.effects.find(e => e.type === "damage_per_card_anywhere") as
    Extract<CardEffect, { type: "damage_per_card_anywhere" }> | undefined;
  const perCardBonus = perCardEff ? perCardEff.amount * player.totalCardsAnywhere : 0;

  // Pre-compute Rampage bonus — accumulated +damage from prior plays this combat
  const rampageBonusEff = card.effects.find(e => e.type === "rampage_bonus") as
    Extract<CardEffect, { type: "rampage_bonus" }> | undefined;
  const rampageBonus = rampageBonusEff ? player.rampageDamageBonus : 0;

  // Pre-compute Thrash bonus — accumulated base-damage bonus from prior Thrash exhausts this turn
  const thrashBonus = card.hasExhaustForDamageBonus ? player.thrashDamageBonus : 0;

  let damage = 0;
  let block  = 0;

  for (const eff of card.effects) {
    switch (eff.type) {
      case "damage": {
        const base = (eff.useCurrentBlock ? player.currentBlock : eff.amount)
                   + strength + exhaustBonus + perCardBonus + rampageBonus + thrashBonus;
        const bonusHits = (eff.bonusHitsIfVulnerable && vulnerableStacks > 0) ? eff.bonusHitsIfVulnerable : 0;
        const hpLossBonus = (eff.hitsPerHpLoss ?? 0) * player.hpLossCount;
        const hits = (card.xCost ? player.energyRemaining : eff.hits) + bonusHits + hpLossBonus;
        damage += Math.floor(base * vulnMult * weakMult * hits);
        break;
      }
      case "block":
        block += Math.floor(eff.amount * (player.doubleNextBlockCard ? 2 : 1) * frailMult);
        break;
      case "orb": {
        const base = ORB_BASE[eff.orbType];
        if (base) {
          if (base.damage > 0) damage += (base.damage + focus) * eff.count;
          if (base.block  > 0) block  += (base.block  + focus) * eff.count;
        }
        break;
      }
      case "poison": {
        const t = poisonTriggers;
        if (t > 0) damage += t * eff.amount - (t * (t - 1)) / 2;
        break;
      }
      case "doom":
        damage += eff.amount;
        break;
      case "weak":
        // Applying Weak to the enemy is modelled as effective block
        if (!player.enemyWeak && player.enemyAttack > 0) {
          block += (player.enemyAttack - Math.floor(player.enemyAttack * 0.75)) * player.enemyHits;
        }
        break;
      case "str_down":
        // Reducing enemy strength is modelled as effective block (not subject to frailMult).
        // Unlike weak (which is a % of enemy attack), str_down is a flat N×hits reduction
        // that is meaningful regardless of the enemy's base attack value.
        block += eff.amount * player.enemyHits;
        break;
      case "block_if_exhausted_turn":
        if (player.exhaustedThisTurn) block += eff.amount;
        break;
      case "damage_per_attack_played":
        damage += eff.amount * player.attacksPlayedThisTurn;
        break;
      case "damage_reduction_if_enemy_vuln":
        // If the enemy is vulnerable, player takes (fraction×100)% less damage from them.
        // Modelled as effective block: damage saved = (attack - floor(attack × (1−fraction))) × hits.
        if (player.vulnerableStacks > 0 && player.enemyAttack > 0) {
          block += (player.enemyAttack - Math.floor(player.enemyAttack * (1 - eff.fraction))) * player.enemyHits;
        }
        break;
      case "thorns":
        // Retaliation damage per enemy hit; only scored when --enemy-attack is set.
        if (player.enemyAttack > 0) damage += eff.amount * player.enemyHits;
        break;
      case "damage_per_vuln_stack":
        damage += eff.amount * player.vulnerableStacks;
        break;
      case "damage_per_self_damage":
        damage += eff.amount * player.selfDamageThisTurn;
        break;
      case "damage_if_self_damaged":
        if (player.selfDamageThisTurn > 0) damage += eff.amount;
        break;

      // Effects pre-computed above and folded into the damage case — no further action here.
      case "exhaust_bonus":
      case "damage_per_card_anywhere":
      case "rampage_bonus":
      case "exhaust_for_damage_bonus":
      // Rage block is applied after the loop via player.blockPerAttackPlayed — no action here.
      case "rage":
      // Turn-structural effects resolved by the turn-simulator, not by scoring.
      case "draw":
      case "draw_if_self_damaged":
      case "draw_until_non_attack":
      case "draw_per_exhaust_event":
      case "exhaust_hand":
      case "exhaust_draw":
      case "upgrade_hand":
      case "discard_to_draw":
      case "copy_to_discard":
      case "play_top_and_exhaust":
      case "cascade":
      case "stampede":
      case "plating":
      // State mutations applied by applyCardState — no contribution to immediate damage/block.
      case "energy_gain":
      case "energy_if_exhausted_turn":
      case "str_gain":
      case "str_gain_per_vuln_stack":
      case "vuln":
      case "double_vuln_stacks":
      case "vuln_mult_bonus":
      case "block_per_exhaust_event":
      case "damage_per_block_gain":
      case "damage_per_hp_loss":
      case "self_damage":
      case "rupture":
      // State set by applyCardState; no immediate scoring contribution.
      case "double_next_block_card":
        break;

      default:
        assertNever(eff);
    }
  }

  // Rage passive: each attack played this turn gains N block
  if (card.type === "attack" && player.blockPerAttackPlayed > 0) {
    block += player.blockPerAttackPlayed;
  }

  if (card.type === "attack" && player.doubleNextAttacks > 0) {
    damage *= 2;
    block  *= 2;
  }

  return { damage, block };
}

// Apply the state changes a card produces when played (for intra-turn sequencing)
export function applyCardState(state: PlayerState, card: Card): PlayerState {
  let next = state;

  for (const eff of card.effects) {
    switch (eff.type) {
      case "str_gain":
        next = { ...next, strength: next.strength + eff.amount };
        break;
      case "str_gain_per_vuln_stack":
        next = { ...next, strength: next.strength + eff.amount * next.vulnerableStacks };
        break;
      case "vuln":
        next = { ...next, vulnerableStacks: next.vulnerableStacks + eff.amount };
        break;
      case "double_vuln_stacks":
        if (next.vulnerableStacks > 0)
          next = { ...next, vulnerableStacks: next.vulnerableStacks * 2 };
        break;
      case "weak":
        next = { ...next, enemyWeak: true };
        break;
      case "str_down":
        next = { ...next, enemyStrength: next.enemyStrength - eff.amount };
        break;
      case "energy_gain":
        if (next.energyRemaining > 0)
          next = { ...next, energyRemaining: next.energyRemaining + eff.amount };
        break;
      case "energy_if_exhausted_turn":
        if (next.energyRemaining > 0 && next.exhaustedThisTurn)
          next = { ...next, energyRemaining: next.energyRemaining + eff.amount };
        break;
      case "vuln_mult_bonus":
        next = { ...next, vulnMultBonus: next.vulnMultBonus + eff.amount };
        break;
      case "block_per_exhaust_event":
        next = { ...next, blockPerExhaustEvent: next.blockPerExhaustEvent + eff.amount };
        break;
      case "damage_per_block_gain":
        next = { ...next, damagePerBlockGain: next.damagePerBlockGain + eff.amount };
        break;
      case "damage_per_hp_loss":
        next = { ...next, damagePerHpLoss: next.damagePerHpLoss + eff.amount };
        break;
      case "draw_per_exhaust_event":
        next = { ...next, drawPerExhaustEvent: next.drawPerExhaustEvent + eff.amount };
        break;
      case "rage":
        next = { ...next, blockPerAttackPlayed: next.blockPerAttackPlayed + eff.amount };
        break;
      case "rampage_bonus":
        next = { ...next, rampageDamageBonus: next.rampageDamageBonus + eff.amount };
        break;
      case "rupture":
        next = { ...next, strengthPerHpLoss: next.strengthPerHpLoss + eff.amount };
        break;
      case "stampede":
        next = { ...next, stampedeCount: next.stampedeCount + 1 };
        break;
      case "plating":
        next = { ...next, plating: next.plating + eff.amount };
        break;
      case "self_damage":
        next = { ...next, selfDamageThisTurn: next.selfDamageThisTurn + 1,
          hpLossCount: next.hpLossCount + 1,
          strength: next.strength + next.strengthPerHpLoss };
        break;
      case "double_next_block_card":
        next = { ...next, doubleNextBlockCard: true };
        break;

      // Damage/block scoring — no state mutation needed here (handled by cardEffectiveValues).
      case "damage":
      case "block":
      case "orb":
      case "poison":
      case "doom":
      case "exhaust_bonus":
      case "damage_per_self_damage":
      case "damage_if_self_damaged":
      case "block_if_exhausted_turn":
      case "damage_per_vuln_stack":
      case "damage_per_attack_played":
      case "damage_reduction_if_enemy_vuln":
      case "thorns":
      case "damage_per_card_anywhere":
      case "rampage_bonus":
      case "exhaust_for_damage_bonus":
      // Turn-structural effects resolved by the turn-simulator — no state mutation here.
      case "draw":
      case "draw_if_self_damaged":
      case "draw_until_non_attack":
      case "exhaust_hand":
      case "exhaust_draw":
      case "upgrade_hand":
      case "discard_to_draw":
      case "copy_to_discard":
      case "play_top_and_exhaust":
      case "cascade":
      case "stampede":
      case "plating":
        break;

      default:
        assertNever(eff);
    }
  }

  // Unmovable: reset after the first block-effect card is played.
  if (state.doubleNextBlockCard && card.effects.some(e => e.type === "block"))
    next = { ...next, doubleNextBlockCard: false };

  // Attacks consume any pending nextAttackFree and doubleNextAttacks; card may set those for the following attack.
  if (card.type === "attack") next = { ...next, attacksPlayedThisTurn: next.attacksPlayedThisTurn + 1, nextAttackFree: false,
    doubleNextAttacks: Math.max(0, next.doubleNextAttacks - 1) };
  if (card.nextAttackFree)    next = { ...next, nextAttackFree: true };
  if (card.skillsFreeExhaust)   next = { ...next, corruptionActive:   true };
  if (card.strikeDrawTrigger)   next = { ...next, hellraiserActive:   true };
  if (card.copyAttackOnN)       next = { ...next, copyAttackOnN: card.copyAttackOnN };
  if (card.doubleNextAttacks)   next = { ...next, doubleNextAttacks: card.doubleNextAttacks };

  const { block } = cardEffectiveValues(card, state);
  if (block > 0) next = { ...next, currentBlock: next.currentBlock + block };
  return next;
}

// Simulate playing a sequence of cards in order, accumulating state as we go
export function simulateCombo(orderedCombo: string[], db: CardDb, player: PlayerState): ComboResult {
  let state = { ...player };
  let totalDamage = 0;
  let totalBlock  = 0;

  for (const name of orderedCombo) {
    const card = db[name];
    if (!card) continue;
    const { damage, block } = cardEffectiveValues(card, state);
    totalDamage += damage;
    totalBlock  += block;
    state = applyCardState(state, card);
  }

  return { totalDamage, totalBlock };
}
